var GLASS = 'background:rgba(8,13,20,.55);backdrop-filter:blur(10px);-webkit-backdrop-filter:blur(10px);border:1px solid rgba(255,255,255,.12);border-radius:12px;';
var MONO = "font-family:'IBM Plex Mono',ui-monospace,monospace;";

export function hudHTML() {
  return [
    '<div style="position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse at center, transparent 55%, rgba(5,10,18,.5));"></div>',
    '<div data-cross style="position:absolute;left:50%;top:50%;width:6px;height:6px;margin:-3px 0 0 -3px;border-radius:50%;background:rgba(255,255,255,.85);box-shadow:0 0 6px rgba(0,0,0,.6);pointer-events:none;opacity:0;transition:opacity .3s;"></div>',
    '<div style="position:absolute;top:16px;left:16px;padding:12px 16px;' + GLASS + 'pointer-events:none;display:flex;flex-direction:column;gap:4px;">',
    '  <div style="font-weight:700;font-size:17px;letter-spacing:.32em;color:#fff;">INFINITE</div>',
    '  <div data-fps style="' + MONO + 'font-size:11px;color:rgba(255,255,255,.6);">\u2014 fps</div>',
    '  <div data-clock style="' + MONO + 'font-size:11px;color:rgba(255,255,255,.75);">\u2014</div>',
    '  <div data-disc style="font-size:12px;color:#8fd8ff;">\u25c6 0 discovered</div>',
    '</div>',
    '<div style="position:absolute;top:16px;right:16px;padding:8px;' + GLASS + 'pointer-events:none;">',
    '  <canvas data-map width="168" height="168" style="display:block;border-radius:8px;"></canvas>',
    '  <div style="position:absolute;top:12px;left:50%;transform:translateX(-50%);' + MONO + 'font-size:10px;color:rgba(255,255,255,.75);text-shadow:0 1px 3px rgba(0,0,0,.8);">N</div>',
    '</div>',
    '<div style="position:absolute;left:16px;bottom:16px;padding:12px 16px;' + GLASS + 'pointer-events:none;min-width:208px;display:flex;flex-direction:column;gap:7px;">',
    '  <div style="display:flex;justify-content:space-between;gap:16px;align-items:baseline;">',
    '    <span style="font-size:10px;letter-spacing:.18em;color:rgba(255,255,255,.5);">BIOME</span>',
    '    <span data-biome style="font-size:13px;font-weight:500;color:#fff;">\u2014</span>',
    '  </div>',
    '  <div style="display:flex;justify-content:space-between;gap:16px;align-items:baseline;">',
    '    <span style="font-size:10px;letter-spacing:.18em;color:rgba(255,255,255,.5);">POS</span>',
    '    <span data-pos style="' + MONO + 'font-size:12px;color:rgba(255,255,255,.85);">0, 0</span>',
    '  </div>',
    '  <div style="display:flex;justify-content:space-between;gap:16px;align-items:center;">',
    '    <span style="font-size:10px;letter-spacing:.18em;color:rgba(255,255,255,.5);">SPEED</span>',
    '    <span style="display:flex;align-items:center;gap:8px;">',
    '      <span style="width:74px;height:4px;border-radius:2px;background:rgba(255,255,255,.14);overflow:hidden;display:inline-block;"><span data-speedbar style="display:block;height:100%;width:0%;border-radius:2px;background:linear-gradient(90deg,#5fb8e8,#8fd8ff);transition:width .15s;"></span></span>',
    '      <span data-speed style="' + MONO + 'font-size:12px;color:rgba(255,255,255,.85);min-width:54px;text-align:right;">0.0 m/s</span>',
    '    </span>',
    '  </div>',
    '</div>',
    '<div data-hint style="position:absolute;right:16px;bottom:16px;padding:8px 14px;' + GLASS + MONO + 'font-size:11px;color:rgba(255,255,255,.62);pointer-events:none;">WASD move \u00b7 mouse look \u00b7 SPACE double-jump \u00b7 SHIFT sprint \u00b7 E discover</div>',
    '<div data-popup style="position:absolute;left:50%;bottom:84px;transform:translate(-50%,10px);max-width:380px;padding:14px 18px;' + GLASS + 'border-color:rgba(143,216,255,.35);pointer-events:none;opacity:0;transition:opacity .25s, transform .25s;text-align:center;">',
    '  <div data-popup-kicker style="' + MONO + 'font-size:10px;letter-spacing:.14em;color:#8fd8ff;margin-bottom:5px;">POINT OF INTEREST</div>',
    '  <div data-popup-name style="font-size:17px;font-weight:700;color:#fff;margin-bottom:6px;">\u2014</div>',
    '  <div data-popup-lore style="font-size:12.5px;line-height:1.5;color:rgba(255,255,255,.78);margin-bottom:9px;">\u2014</div>',
    '  <div data-popup-action style="' + MONO + 'font-size:11px;color:#ffd86b;">[ E ] DISCOVER</div>',
    '</div>',
    '<div data-start style="position:absolute;inset:0;display:none;align-items:center;justify-content:center;background:rgba(5,9,16,.42);cursor:pointer;">',
    '  <div style="text-align:center;padding:22px 34px;' + GLASS + '">',
    '    <div style="font-size:15px;font-weight:700;letter-spacing:.26em;color:#fff;margin-bottom:8px;">\u25b6 CLICK TO EXPLORE</div>',
    '    <div style="' + MONO + 'font-size:11px;color:rgba(255,255,255,.6);">pointer locks for mouse-look \u00b7 ESC releases</div>',
    '  </div>',
    '</div>',
    '<div data-loading style="position:absolute;inset:0;display:flex;align-items:center;justify-content:center;background:#0a0e14;transition:opacity .6s;z-index:5;">',
    '  <div style="text-align:center;">',
    '    <div style="font-size:22px;font-weight:700;letter-spacing:.42em;color:#fff;margin-bottom:18px;">INFINITE</div>',
    '    <div style="width:220px;height:3px;border-radius:2px;background:rgba(255,255,255,.12);margin:0 auto 12px;overflow:hidden;"><div data-loadbar style="height:100%;width:0%;background:#8fd8ff;border-radius:2px;transition:width .2s;"></div></div>',
    '    <div data-loadtext style="' + MONO + 'font-size:11px;color:rgba(255,255,255,.55);">compiling shaders \u00b7 generating terrain</div>',
    '  </div>',
    '</div>'
  ].join('');
}
