export var TERRAIN_VERT = [
  'attribute float aAO;',
  'varying vec3 vWorld;',
  'varying vec3 vNormal;',
  'varying float vAO;',
  'void main() {',
  '  vec4 wp = modelMatrix * vec4(position, 1.0);',
  '  vWorld = wp.xyz;',
  '  vNormal = normalize(mat3(modelMatrix) * normal);',
  '  vAO = aAO;',
  '  gl_Position = projectionMatrix * viewMatrix * wp;',
  '}'
].join('\n');

export var TERRAIN_FRAG = [
  'uniform vec3 uSunDir;',
  'uniform vec3 uAmbient;',
  'uniform vec3 uSunCol;',
  'uniform vec3 uFogColor;',
  'uniform float uFogNear;',
  'uniform float uFogFar;',
  'varying vec3 vWorld;',
  'varying vec3 vNormal;',
  'varying float vAO;',
  'float hash21(vec2 p) { p = fract(p * vec2(123.34, 456.21)); p += dot(p, p + 45.32); return fract(p.x * p.y); }',
  'float vn2(vec2 p) {',
  '  vec2 i = floor(p); vec2 f = fract(p); f = f * f * (3.0 - 2.0 * f);',
  '  float a = hash21(i), b = hash21(i + vec2(1.0, 0.0));',
  '  float c = hash21(i + vec2(0.0, 1.0)), e = hash21(i + vec2(1.0, 1.0));',
  '  return mix(mix(a, b, f.x), mix(c, e, f.x), f.y);',
  '}',
  'void main() {',
  '  vec3 n = normalize(vNormal);',
  '  float h = vWorld.y;',
  '  float slope = 1.0 - n.y;',
  '  float detail = vn2(vWorld.xz * 0.9) * 0.65 + vn2(vWorld.xz * 3.7) * 0.35;',
  '  float vary = vn2(vWorld.xz * 0.045);',
  '  float rockAmt = smoothstep(0.30, 0.52, slope + (detail - 0.5) * 0.12);',
  '  float nb = vn2(vWorld.xz * 1.6);',
  '  vec3 pn = vec3(vn2(vWorld.xz * 1.6 + vec2(0.31, 0.0)) - nb, 0.0, vn2(vWorld.xz * 1.6 + vec2(0.0, 0.31)) - nb);',
  '  n = normalize(n + pn * 2.4 * rockAmt);',
  '  vec3 colSea   = vec3(0.13, 0.22, 0.21);',
  '  vec3 colSand  = vec3(0.76, 0.68, 0.48);',
  '  vec3 colGrass = mix(vec3(0.23, 0.37, 0.18), vec3(0.34, 0.46, 0.22), vary);',
  '  vec3 colRock  = mix(vec3(0.38, 0.36, 0.35), vec3(0.46, 0.44, 0.42), vary);',
  '  vec3 colSnow  = vec3(0.92, 0.94, 0.97);',
  '  vec3 col = mix(colSea, colSand, smoothstep(-1.8, 0.5, h));',
  '  col = mix(col, colGrass, smoothstep(1.0, 3.6, h));',
  '  col = mix(col, colRock, rockAmt);',
  '  col = mix(col, colSnow, smoothstep(33.0, 40.0, h + (detail - 0.5) * 5.0) * (1.0 - smoothstep(0.25, 0.55, slope)));',
  '  col *= 0.86 + 0.26 * detail;',
  '  float diff = max(dot(n, uSunDir), 0.0);',
  '  vec3 light = uAmbient + uSunCol * diff * 1.25;',
  '  vec3 view = normalize(cameraPosition - vWorld);',
  '  vec3 hv = normalize(uSunDir + view);',
  '  float spec = pow(max(dot(n, hv), 0.0), 48.0);',
  '  float specAmt = 0.5 * smoothstep(33.0, 40.0, h) + 0.15 * smoothstep(0.5, -0.5, h);',
  '  vec3 c = col * vAO * light + spec * specAmt * uSunCol * 1.3;',
  '  float fog = smoothstep(uFogNear, uFogFar, length(cameraPosition - vWorld));',
  '  c = mix(c, uFogColor, fog);',
  '  gl_FragColor = vec4(c, 1.0);',
  '}'
].join('\n');
